USER=""
PASSWORD=""
HOST="localhost"
PORT=
DATABASE="management"

DB_USER = ""	
DB_PASSWORD = ""	
DB_HOST = ""	
DB_PORT = 	
DB_DATABASE = ""	


EVENT_DB_USER = ""	
EVENT_DB_PASSWORD = ""	
EVENT_DB_HOST = ""	
EVENT_DB_PORT = 	
EVENT_DB_DATABASE = ""	

