USER="root"
PASSWORD="karaveddy2015"
HOST="localhost"
PORT=3306
DATABASE="management"

DB_USER = "root"	
DB_PASSWORD = "karaveddy2015"	
DB_HOST = "localhost"	
DB_PORT = 3306	
DB_DATABASE = "management"	


EVENT_DB_USER = "root"	
EVENT_DB_PASSWORD = "karaveddy2015"	
EVENT_DB_HOST = "localhost"	
EVENT_DB_PORT = 3306	
EVENT_DB_DATABASE = "management"	

